var questions = 4;
var questionsLeft = ' [' + questions + ' questions left]';
var pnoun = prompt('Please type a plural noun' + questionsLeft);
questions -= 1;
questionsLeft = ' [' + questions + ' questions left]';
var noun = prompt('Please type a noun' + questionsLeft);
questions -= 1;
questionsLeft = ' [' + questions + ' questions left]';
var noun2 = prompt('Please type another noun' + questionsLeft);
var questionsLeft = ' [' + questions + ' questions left]';
var song = prompt('Please name a song' + questionsLeft);
questions -= 1;
var questionsLeft = ' [' + questions + ' questions left]';
var verb = prompt('Please type a verb' + questionsLeft);
alert('All done. Ready for the message?');
var sentence = "<h2>For some reason all the " + pnoun;
sentence += ' wanted to hear the song ' + song;
sentence += ' played using the ' + noun;
sentence += '. All we had was the ' + noun2;
sentence += ', so not much could be done. Unfortunately they started to ' + verb + ' all over the place.</h2>';
document.write(sentence);